### ISSUE TITLE
Q1) Repository 패턴을 왜 사용하는 걸까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-2#1]

**Comment by KamaTAEWOO** [comment]
@ows3090 
처음에는 Repository가 왜 필요한지 모르고 있었고, 저런 패턴이 있었는지도 몰랐습니다. 그래서 저는 Repository 패턴을 알기 전에 MainActivity에서 데이터를 요청하고 가지고 와서 Model에 넣어주는 형식을 사용하였습니다. 

알고 난 후 Repository는 외부 데이터를 가지고 오는 함수를 넣고 거기서만 데이터를 가지고 와서 Model에 넣어주고 MainActivity에서는 Model에 있는 데이터만 가지고 와서 사용하면 되니깐 굉장히 편리함을 느꼈습니다. 그리고 유지보수도 매우 편리하고 MainActivity 소스를 볼 때도 편하다는 것을 느꼈습니다.

Repository를 사용하면서 이점들은
1. 코드 관리 용이성: 분리 시키니깐 편했음
2. 유연성: 외부에서 가지고 오는 데이터가 변하더라도 쉽게 변경 가능
3. 테스트 용이성: 의존성 주입을 통해 데이터 소스를 대체할 수 있음.
4. 성능개선: 반복적인 요청에 대한 성능을 향상 시킬 수 있음.

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
Repository 이점들이 말씀하신것도 맞지만 가장 중요한 것은 데이터 소스로부터 추상화 역할을 하게 되는 것입니다.
안드로이드 앱에서 데이터 소스는 보통 네트워크(API), 로컬(DB), 파일 등으로부터 얻어올 수 있습니다.
각각 데이터 소스마다 인터페이스를 공통적으로 정하고 같은 인터페이스로만 가져오도록 하는게 가장 큰 장점입니다.

한번 Repository 패턴에 대해 조금 더 조사해보고 어떤 식으로 코드를 사용하는 지도 작성해주세요~
보통 Repository 인터페이스를 만들고 RepositoryImpl(구현체)를 클래스로 생성하는 방식을 사용하니 해당 코드가 된 걸 참고해주세요

**Comment by KamaTAEWOO** [comment]
@ows3090 

// repository 로그인 할 때 User의 정보를 요청하는 함수 입니다.
interface SignRepository {

    suspend fun getUserInfo(
        uid: String? = "",
    ): Call<UserInfo>
}

// repositoryImpl 구현 함수 입니다. 
class SignRepositoryImpl constructor(
    val service: RetrofitService
) : SignRepository {

    override suspend fun getUserInfo(
        uid: String?,
    ): Call<UserInfo> {
        return service.get_userInfo(uid)
    }
}

**Comment by ows3090** [comment]
@KamaTAEWOO 이해하셨으면 종료하셔도 됩니다.
