### ISSUE TITLE
Q9) Gradle이 뭘까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-2#10]

**Comment by KamaTAEWOO** [comment]
@ows3090 
정의: 안드로이드 앱을 빌드하는데 사용되는 오픈 소스 빌드 자동화 시스템
1. 라이브러리 관리: 개발자가 라이브러리를 추가하고 관리하는데 시간을 절약
2. 빌드속도: 이전 빌드를 기억하여 재 컴파일하지 않고, 빠르게 빌드 가능
3. 다양한 환경지원: 다양한 언어 지원
4. 유연성: 빌드 스크립트를 작성할 때 매우 유연
5. 안전성: 빌드 중에 발생하는 오류를 자동으로 처리하여 빌드 과전을 안정적으로 유지

**Comment by KamaTAEWOO** [comment]
@ows3090  질문들이 너무 좋아서 공부하기 너무 좋은 것 같습니다. 몰랐던 것이나 강의에서 들은 것들을 하나씩 떠올리면서 적고 있는데 너무 좋습니다 ㅎㅎ 감사합니다!!

**Comment by ows3090** [comment]
@KamaTAEWOO 이슈 종료하셔도 됩니다.
