### ISSUE TITLE
Q2) SharedPreference의 Edit에 commit과 apply가 존재하는데 정확하게 차이가 뭘까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-2#2]

**Comment by KamaTAEWOO** [comment]
@ows3090 
commit()은 즉시 결과를 반환하므로 다른 작업을 할 수 없고, 결과를 반환하는 작업부터 시행 후 다음 작업 진행(동기적)
apply()는 결과를 저장하는 동안 다른 작업을 진행 할 수 있다는 장점이 있음. (비동기적)

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
SharedPreference로 값을 작성하게 되면 앱이 종료되더라도 유지된다는 것은 알고 있을 것 같아요
혹시 그럼 SharedPreference 값을 어디에 저장되길래 유지되는 걸까요?

**Comment by KamaTAEWOO** [comment]
@ows3090 SharedPreference를 사용하여 값을 저장하면 휴대폰 내부 저장소에 저장되는 것으로 알고 있습니다.

**Comment by ows3090** [comment]
@KamaTAEWOO 실제로 사용해보면서 Device Explorer를 볼 기회가 생기면 확인해보면 좋을것 같아요
이슈 종료하셔도 됩니다.
